import { Category } from "@/types";

export const defaultCategories: Category[] = [
  // Income categories
  {
    id: "income-salary",
    name: "Salary",
    type: "income",
    icon: "Briefcase",
    color: "#00B894",
    isFrequent: true,
  },
  {
    id: "income-freelance",
    name: "Freelance",
    type: "income",
    icon: "Laptop",
    color: "#55EFC4",
    isFrequent: true,
  },
  {
    id: "income-investments",
    name: "Investments",
    type: "income",
    icon: "TrendingUp",
    color: "#00CEC9",
    isFrequent: false,
  },
  {
    id: "income-gifts",
    name: "Gifts",
    type: "income",
    icon: "Gift",
    color: "#74B9FF",
    isFrequent: false,
  },
  {
    id: "income-other",
    name: "Other Income",
    type: "income",
    icon: "Plus",
    color: "#6C5CE7",
    isFrequent: false,
  },

  // Expense categories
  {
    id: "expense-food",
    name: "Food & Dining",
    type: "expense",
    icon: "Utensils",
    color: "#FF7675",
    isFrequent: true,
  },
  {
    id: "expense-shopping",
    name: "Shopping",
    type: "expense",
    icon: "ShoppingBag",
    color: "#FD79A8",
    isFrequent: true,
  },
  {
    id: "expense-transportation",
    name: "Transportation",
    type: "expense",
    icon: "Car",
    color: "#FDCB6E",
    isFrequent: true,
  },
  {
    id: "expense-utilities",
    name: "Utilities",
    type: "expense",
    icon: "Zap",
    color: "#E17055",
    isFrequent: true,
  },
  {
    id: "expense-housing",
    name: "Housing",
    type: "expense",
    icon: "Home",
    color: "#D63031",
    isFrequent: false,
  },
  {
    id: "expense-entertainment",
    name: "Entertainment",
    type: "expense",
    icon: "Film",
    color: "#E84393",
    isFrequent: false,
  },
  {
    id: "expense-health",
    name: "Health",
    type: "expense",
    icon: "Activity",
    color: "#FF9FF3",
    isFrequent: false,
  },
  {
    id: "expense-education",
    name: "Education",
    type: "expense",
    icon: "Book",
    color: "#F368E0",
    isFrequent: false,
  },
  {
    id: "expense-other",
    name: "Other Expenses",
    type: "expense",
    icon: "MoreHorizontal",
    color: "#636E72",
    isFrequent: false,
  },
];